#955 - Improved the progress bar to match figma
hackforla/expunge-assist pull request #1040
Opened 2023-10-12 23:27 UTC by ramankala

Refactored the progress bar so that the UI would look better for the user to look at.

#955

2023-10-16 20:42 UTC, sydneywalcoff requested changes
Hey Raman! 

Can you refactor this to use material UI for styling?

2023-10-16 20:42 UTC, sydneywalcoff commented on products/statement-generator/src/components/FormHeader.tsx
> +        <h3 className="formTitle">{formTitle}</h3>
rather than importing an external css file and creating a 'formTitle' class inline, can you use Material UI and create a class that way?

2023-10-16 20:42 UTC, sydneywalcoff commented on products/statement-generator/src/styles/App.css
lets remove this and use material ui to style it.

2023-11-10 01:22 UTC, sydneywalcoff requested changes
Hey @ramankala! Desktop looks great! Great job translating to material ui.

The progress bar should get a little smaller as the screen sizes get smaller. I noticed the original figma link I gave you doesn't work anymore, let me know if this is ever a problem again.

for the small breakpoint and below, can you reduce the padding/margin a little bit?

2023-11-11 17:48 UTC, sydneywalcoff requested changes
@ramankala sorry I should have been clearer. I would like the size of the progress bar to remain the same at desktop, but at smaller screen sizes, I'd like to see these changes.

2024-01-14 19:54 UTC, sydneywalcoff requested changes
Hey @ramankala! 

Check #955 for the figma that design added before the break. There's a couple inconsistencies between your branch and the figma.

2024-01-16 01:04 UTC, sydneywalcoff requested changes
Hey @ramankala, 

Just a few comments below. I was also experiencing a responsiveness bug, but I think addressing the issues below might fix it.

2024-01-16 01:04 UTC, sydneywalcoff commented on products/statement-generator/src/components/FormHeader.tsx
> +        '@media (max-height:759px)': {
Also, should this be max-width instead of max-height?

2024-01-16 01:04 UTC, sydneywalcoff commented on products/statement-generator/src/components/ProgressBar.tsx
> +      '@media (min-height: 749px)': {
Same thing here about min-width v min-height

2024-01-22 21:31 UTC, ramankala commented on products/statement-generator/src/components/ProgressBar.tsx
> +      '@media (min-height: 749px)': {
I added `breakpoints.down` to FormHeader.tsx, not sure how I can implement it to ProgressBar.tsx though.  The current pushed commit seems to work for me, let me know how I can add it to ProgressBar.tsx if it's still needed.

2024-01-23 03:11 UTC, sydneywalcoff requested changes
@ramankala I know you didn't get a tablet design. But between 400-767px, there are points when the progress bar is shorter than the rest of the content.
<img width="553" alt="Screen Shot 2024-01-22 at 7 05 36 PM" src="https://github.com/hackforla/expunge-assist/assets/75542938/769375fb-24f3-4134-b96e-17c591f2bb11">

Can you apply the mobile styles (where the progress bar goes all the way across) starting at 767?

2024-01-26 01:39 UTC, sydneywalcoff requested changes
@ramankala Visually, its perfect! Great job!

I just need you to run prettier using `npm run lint:fix` and we can get this merged 🎉

2024-02-01 04:09 UTC, sydneywalcoff approved these changes
Looks good @ramankala !! 🎉

2024-02-01 04:09 UTC, merged