#1151 Letter Generator Progress Bar Bug
hackforla/expunge-assist pull request #1162
Opened 2024-02-15 19:28 UTC by davidwiese

### **Fixes** #1151

**Issue:**

The `FormHeader` (including `ProgressBar`) would continue to display if a user clicked on a footer link from anywhere within the form.

**Solution:**

Implement useLocation hook to keep track of the current URL, then conditionally render the FormHeader with CSS when the user is on a form page `https://expungeassist.org/form/`, `https://expungeassist.org/form/intro`, etc. -- otherwise it is hidden.

2024-02-21 03:30 UTC, sydneywalcoff requested changes
@davidwiese This works, but we still don't know why the formHeader is being shown on pages where it's not being called.

Can you re-evaluate with that in mind?

2024-02-22 22:30 UTC, davidwiese commented
> @davidwiese This works, but we still don't know why the formHeader is being shown on pages where it's not being called.
> 
> Can you re-evaluate with that in mind?

@sydneywalcoff Ok I dug into this a bit today, and it has to do w/ how the app is structured overall.

In the main `App.tsx` file, the `AppHeader` and `AppSubheader` components are rendered outside and above the `Switch` component from `react-router-dom`. This structure means that `AppHeader` and `AppSubheader` (where the formHeader with the status bar is called) are always rendered regardless of the current route. This is why the `formHeader` and status bar is shown on pages even where it's not explicitly called by the route's component.

So ultimately the issue arises because `AppSubheader` is not contextually aware of the route it's being rendered on... it simply renders unconditionally at the top level of the app. Changing this behavior would involve restructuring the logic and contexts behind how the entire app is rendered.

2024-03-06 21:08 UTC, sydneywalcoff requested changes
@davidwiese yes to all of that AND there has to be something else additionally because the `AppSubHeader` doesn't show on the Landing Page (ever) and isn't persistent on the other non-form pages (If you click to the LP and back again, it doesn't show anymore). Bonus points for figuring out the _why_ behind this bug. 

Secondarily I realized there's a more elegant fix that we've used in other places on the site, so I added a comment with my suggestion.

We already have a state mangement to handle the routing. We're using React Context, (check out RoutingContext.tsx) but eventually maybe we'll need to transition to redux.

2024-03-06 21:08 UTC, sydneywalcoff commented on products/statement-generator/src/components/FormHeader.tsx
> +
Rather than handling this with a custom 'hidden' class, we should use the location to return early if `isFormRoute` is true.

2024-03-06 23:07 UTC, davidwiese commented
@sydneywalcoff First- I made the changes using your more elegant solution of returning early.

Second - I think I've wrapped my head around why it doesn't show on the LP and doesn't persist on other non-form pages -- it's due to the way the `RoutingContext` provider manages the `appHistory` and `currentStep` state.

When navigating to the Landing Page `(/)`, the `useEffect` hook in the `RoutingContext` provider resets the `appHistory` to `[AppUrl.Landing]` and sets the `historyIdx` to `0`. This means that the `currentStep` is no longer a form page, causing the `AppSubHeader` to not render the `FormHeader`.

Similarly, when navigating to other non-form pages (e.g., `/404`, `/privacy-policy`), the `currentStep` is set to the corresponding `AppUrl` (e.g., `AppUrl.NotFound`, `AppUrl.PrivacyPolicy`). These routes are not considered form pages, so the `AppSubHeader` doesn't render the `FormHeader`.

When navigating back from the Landing Page or other non-form pages to a previously visited form page, the `handleBrowserPageNav` function is called. However, since the `appHistory` was reset when navigating to the Landing Page or non-form page, the `currentStep` no longer matches a form page. As a result, the `AppSubHeader` doesn't render the `FormHeader`.

The root cause of this behavior lies in the `useEffect` hook that resets the `appHistory` and `currentStep` when navigating to the Landing Page or non-form pages. This causes the `isFormPage` check in the `AppSubHeader` component to return `false`, resulting in the `FormHeader` not being rendered.

To resolve this issue, we would need to modify the logic in the `RoutingContext` provider to handle the `appHistory` and `currentStep` state differently when navigating to the Landing Page/non-form pages. Instead of resetting the `appHistory` and `currentStep`, we may want to maintain the form page history and only update the `currentStep` when navigating to a form page.

By making these changes, the `AppSubHeader` should persist on non-form pages when navigating back from the Landing Page or other non-form pages, as the `currentStep` would still match a form page, allowing the `FormHeader` to be rendered.

2024-03-07 19:40 UTC, sydneywalcoff approved these changes
@davidwiese Great job on solving this and providing such a detailed analysis about the root cause of the bug. 💯 🎉

2024-03-07 19:40 UTC, merged