1172 fix faq alignment
hackforla/expunge-assist pull request #1258
Opened 2024-03-14 22:52 UTC by davidwiese

Fixes #1172 

### Changes made

- Adjusted `AppFooter` to exactly match and align with `AppHeader` - otherwise none of the content would be aligned with both
- Adjusted `FAQHeader` content width to stay aligned with the `AppHeader` and `AppFooter`
- Adjusted `FAQHeader` text and image to have correct line numbers and spacing
- Adjusted `FAQContainer` content width to stay aligned with the `AppHeader` and `AppFooter`

### Reason for changes

- Implementation of the FAQ page did not match design team's wireframes. It has a more polished/professional look and feel now

2024-03-16 23:15 UTC, sydneywalcoff requested changes
Hey @davidwiese! This looks really good. I left one request, but it's pretty small.

2024-03-16 23:15 UTC, sydneywalcoff commented on products/statement-generator/src/components-layout/AppFooter.tsx
> +        marginLeft: '-8px',
here as well, please

2024-03-16 23:15 UTC, sydneywalcoff commented on products/statement-generator/src/components-layout/AppFooter.tsx
> +      },
Because the weird footer alignment is caused by padding, best practice would say to adjust the padding before implementing a negative margin.

2024-03-21 18:11 UTC, davidwiese commented
> Hey @davidwiese! This looks really good. I left one request, but it's pretty small.

@sydneywalcoff Made adjustments to get everything lined up at all breakpoints without negative margins

2024-03-25 20:58 UTC, sydneywalcoff approved these changes
@davidwiese looks great! Thank you for making those changes!!

2024-03-25 20:58 UTC, merged