1316 Add GHA to automate weekly label check for issues
hackforla/expunge-assist pull request #1380
Opened 2024-05-03 00:38 UTC by eburdekin

Fixes #1316 

Quick note - while testing this locally with Act, I actually applied “priority: missing” labels to 4 issues. Glad it worked properly, but sorry about that 😅 I’ll look into why that happened.

**Changes made**: Added a GitHub Action that runs on Sundays and filters through open issues in the repo, adding missing labels where necessary. 

**Reason for changes**: Currently the weekly label check is really onerous. You have to go link by link to update and add `missing` labels to all the issues missing any of the required labels.

I emulated the website team’s GHA setup here for a similar workflow that runs when an issue is opened or assigned:
- Wiki page [here](https://github.com/hackforla/website/wiki/Hack-for-LA's-GitHub-Actions)
- .yml [here](https://github.com/hackforla/website/blob/gh-pages/.github/workflows/issue-trigger.yml)
- .js [here](https://github.com/hackforla/website/blob/gh-pages/github-actions/trigger-issue/add-missing-labels-to-issues/check-labels.js)

‘What do you think about adding a function to comment on the issues like they have [here](https://github.com/hackforla/website/blob/gh-pages/github-actions/trigger-issue/add-missing-labels-to-issues/add-labels-template.md)?

2024-05-04 19:57 UTC, sydneywalcoff requested changes
@eburdekin Yay! This is so exciting! I added a comment below with a some small requests, but I'm excited to get this going 🎉

2024-05-04 19:57 UTC, sydneywalcoff commented on .github/workflows/scripts/weekly-label-check.js
> +];
lets also add `issue level` as a required label and `issue level: missing` as a missing label. It's not technically part of the audit, but lets encourage people to use them. 


Secondly for scalability, can we create the `LABEL_MISSING` array dynamically from the `REQUIRED_LABELS` array? They all follow the `[REQUIRED_LABELS]: missing` pattern.

2024-05-04 21:02 UTC, eburdekin commented
Thanks @sydneywalcoff ! Should be all set here.

2024-05-06 19:22 UTC, sydneywalcoff approved these changes
@eburdekin yay! Thank you!

2024-05-06 19:22 UTC, merged