1363 auto correct form fields
hackforla/expunge-assist pull request #1407
Opened 2024-05-22 19:02 UTC by davidwiese

Fixes #1363 

### Changes made
Updated all form inputs to properly capitalize or add punctuation as necessary within the context of the generated form. Tested edge cases as I encountered or thought of them.

### Reason for changes
This makes the LG more user friendly, and will require the user to make fewer edits on the preview pages. It will also help prevent their letter from looking unpolished.

2024-05-29 19:43 UTC, sydneywalcoff requested changes
@davidwiese firstly, thank you for fixing that variable typo lol.

secondly, since a lot of the code to check for capitalization/punctuation is the same, can we refactor it into a reusable helper function?

2024-06-05 18:05 UTC, davidwiese commented
@sydneywalcoff 

Made the changes where able

2024-06-05 20:59 UTC, sydneywalcoff requested changes
@davidwiese great work! I'd like to turn the 'article' logic into a 'generateArticle' function and add to the helpers. Should be a pretty quick change.

2024-06-05 20:59 UTC, sydneywalcoff commented on products/statement-generator/src/helpers/statementGenerators.ts
> +  const article = /^[aeiou]/i.test(jobTitle) ? 'an' : 'a';
lets make a 'generateArticle' helper function too.

2024-06-05 21:31 UTC, davidwiese commented on products/statement-generator/src/helpers/statementGenerators.ts
> +  const article = /^[aeiou]/i.test(jobTitle) ? 'an' : 'a';
All set @sydneywalcoff

2024-06-12 02:23 UTC, sydneywalcoff requested changes
@davidwiese thank you for making those changes re: refactoring!! 

I'm unsure if this bug was present last time I checked and I just missed it, but when running locally, I'm not seeing the Capitalization and Punctuation being implemented on some(but not all) of the textarea components. I noticed it primarily on the ones with (2-3 sentences) in the prompt.

2024-06-12 16:45 UTC, davidwiese commented
> @davidwiese thank you for making those changes re: refactoring!!
> 
> I'm unsure if this bug was present last time I checked and I just missed it, but when running locally, I'm not seeing the Capitalization and Punctuation being implemented on some(but not all) of the textarea components. I noticed it primarily on the ones with (2-3 sentences) in the prompt.

@sydneywalcoff Hmmm I just ran through it and tested every field possible. I didn't encounter this bug anywhere.

2024-06-12 17:02 UTC, davidwiese commented
@sydneywalcoff Added an additional helper to capitalize standalone "I" in the LG form fields

2024-06-27 21:38 UTC, sydneywalcoff approved these changes
@davidwiese this looks great! I re-tested it with manually typed answers and it worked perfectly. Eventually we may want to expand this to also apply when the user edits the responses, but for the time being, I think this is wonderful. Thank you for taking this on!

2024-06-27 21:38 UTC, merged