1247 Textarea testing
hackforla/expunge-assist pull request #1490
Opened 2024-07-26 07:15 UTC by eburdekin

Fixes #1247 

### Changes made: 
Added tests for the following:
- textarea renders and displays the correct default value
- textarea props are passed correctly
- textarea is accessible and focusable

### Reason for changes:
We want to retroactively implement testing to better protect our codebase

2024-08-11 20:55 UTC, sydneywalcoff requested changes
@eburdekin Hey Eileen!

These look great I had one small suggestion below!

2024-08-11 20:55 UTC, sydneywalcoff commented on products/statement-generator/src/tests/textareas.test.tsx
> +    expect(input).toHaveFocus();
There are other ways to focus on a text area, like tabbing from the a different element. Our tests should cover that as well.

2024-08-12 05:06 UTC, eburdekin commented
Thanks @sydneywalcoff ! Added tests to account for tabbing onto the elements.

2024-09-24 01:49 UTC, sydneywalcoff approved these changes
@eburdekin Looks great! Thank you for making that accessibility addition!

2024-09-24 01:49 UTC, merged