#704 update landing page
hackforla/expunge-assist pull request #748
Opened 2022-11-15 17:56 UTC by davidemmolino

- Installed additional MUI packages to support dropdown and icons for new designs
- bumped types/react version to support MUI packages
- updated and removed unused text
- created an accordions component

**Preview screenshots**
![Screen Shot 2022-11-14 at 4 32 19 PM](https://user-images.githubusercontent.com/22949335/201991056-c2bb976d-07fc-4917-b49a-9b0d6dd0d56f.png)
![Screen Shot 2022-11-14 at 4 32 24 PM](https://user-images.githubusercontent.com/22949335/201991064-259190f5-3e67-437e-88b1-bef661638fa1.png)
![Screen Shot 2022-11-14 at 4 32 27 PM](https://user-images.githubusercontent.com/22949335/201991071-05c7319a-786f-4881-8ff1-60f573139d4e.png)
![Screen Shot 2022-11-14 at 4 32 32 PM](https://user-images.githubusercontent.com/22949335/201991080-357468c1-4305-4aec-acb6-28700e27cc14.png)
![Screen Shot 2022-11-14 at 4 57 23 PM](https://user-images.githubusercontent.com/22949335/201991087-7bf685e7-aeb1-42ef-bfcc-dea84d8623a7.png)

**Before** changes
![Screen Shot 2022-11-14 at 4 27 41 PM](https://user-images.githubusercontent.com/22949335/201991120-5a9558c7-2d73-41bd-aa59-5f17e46013e8.png)

**After** changes
![Screen Shot 2022-11-14 at 4 32 12 PM](https://user-images.githubusercontent.com/22949335/201991047-d2aadb03-746e-492c-937a-6e5ccc3bf46a.png)

2022-11-15 18:10 UTC, davidemmolino commented
Performance is really low, might be due to having a bunch of PNG's on the page. Although, pretty sure Lighthouse is doing it's performance test on the development build of the site. Might be better in prod version of the build.

Not sure if you want to consider lazy loading a landing page or fetching those images from a remote database.

I heard MUI isn't great in terms of performance and that a headless UI could be a better and less bloated option but if we're on a time crunch it's probably best to put the idea on the backburner.

2022-11-27 23:00 UTC, aahvocado requested changes
Sweet, thanks for the big chunk of work! I left some comments inline. I'll be sure to respond quicker this time.

I'm going to see if I can ask design for .svg files to reduce that initial load size because these images do indeed have a big hit on performance.

2022-11-28 05:51 UTC, davidemmolino commented on .gitignore
> +.idea/*
done

2022-11-29 00:32 UTC, davidemmolino commented on products/statement-generator/package.json
> +    "@mui/material": "^5.10.13",
icons-material is for the arrow in the accordion, don't necessarily need it.
The rest are needed to generate the MUI accordion itself. 
Are you suggesting just building the accordion from scratch?

2022-11-29 00:47 UTC, davidemmolino commented on products/statement-generator/src/components/Accordions.tsx
> +    transform: 'rotate(90deg)',
Updated

2022-11-29 01:44 UTC, davidemmolino commented on products/statement-generator/package.json
> +    "@mui/material": "^5.10.13",
Also found this info which I thought was interesting.. Don't usually work with MUI so it was nice to learn
https://mui.com/material-ui/guides/minimizing-bundle-size/

2022-12-04 19:39 UTC, aahvocado commented on products/statement-generator/package.json
> +    "@mui/material": "^5.10.13",
> icons-material is for the arrow in the accordion, don't necessarily need it. The rest are needed to generate the MUI accordion itself. Are you suggesting just building the accordion from scratch?

What I mean is we already have material-ui v4 which has an [accordion component](https://v4.mui.com/components/material-icons/#material-icons) and the [arrows](https://v4.mui.com/components/material-icons/#material-icons) if you look for ExpandMore and ExpandLess. No need to bring in another package with v5

2022-12-05 01:45 UTC, davidemmolino commented on products/statement-generator/package.json
> +    "@mui/material": "^5.10.13",
I see, sorry but both links go to the same url could you update the url for accordion, please?

2023-02-04 20:18 UTC, sydneywalcoff commented
Closing this, as it's less work to just rebuild this.

2023-02-04 20:18 UTC, closed without merging