#694: Update before you begin copy
hackforla/expunge-assist pull request #912
Opened 2023-04-19 19:10 UTC by tglaz

### Update before you begin copy #694

Action Items
- [x] Update before you begin copy
- [x] Add URLs for Privacy Policy, Terms of Use, and FAQ pages before testing

**Note**:  Using `dangerouslySetInnerHTML` to render HTML <a> links  from translation file.

<img width="400" alt="image" src="https://user-images.githubusercontent.com/437097/233175602-8cbf8ba1-e48a-430b-9d8a-784ffed28911.png">

<img width="650" alt="image" src="https://user-images.githubusercontent.com/437097/233175689-72c7d7cd-c426-4dca-b24c-b568bc7d02a3.png">

2023-04-25 01:23 UTC, sydneywalcoff requested changes

2023-04-25 01:23 UTC, sydneywalcoff commented on products/statement-generator/public/locales/en/translation.json
> +    "sectionParagraph1": "Be sure you are eligible to have your record cleared. If you’re not sure, here are <a href='https://roadmap.rootandrebound.org/understanding-cleaning-up-your-criminal-record
@tglaz also this copy references two resources, but only one is linked.

@SamHyler Is there a second resource to link or should we update the copy?

2023-04-25 04:17 UTC, tglaz commented on products/statement-generator/public/locales/en/translation.json
> +    "sectionParagraph1": "Be sure you are eligible to have your record cleared. If you’re not sure, here are <a href='https://roadmap.rootandrebound.org/understanding-cleaning-up-your-criminal-record
@sydneywalcoff  - href updated to open in new tab
Regarding the link i'll wait for Sam's response.

@SamHyler  - The link in question is with the copy below. In Figma there is only one link for the `two resources` copy. 

> _Be sure you are eligible to have your record cleared. If you’re not sure, here are `two resources` to help._

2023-05-05 17:08 UTC, SamHyler commented
Two links come up for me. https://roadmap.rootandrebound.org/understanding-cleaning-up-your-criminal-record/cleaning-up-your-criminal-record-later-in-reentry/california-expungement-of-state-convictions/chart-which-type-of-expungement-am-i-eligible-for/
and 
https://www.robertmhelfend.com/criminal-defense/how-get-felony-expunged-california/#6-step-2-find-out-if-you-are-eligible-for-expungement

They are each linked to one respective word. There might be a better way of indicating that there are two resources for folks. Maybe "here and here are two resources to help" with links on each "here" is a better copy for this to avoid confusion. Let me know if you go with that and I'll update the Figma frames

2023-05-12 00:09 UTC, sydneywalcoff commented
@tglaz are you able to update the links like Sam mentioned above?

2023-05-12 04:15 UTC, tglaz commented
@SamHyler  - how about just using the article titles like below, except that they'd be underlined and not italic?

Be sure you are eligible to have your record cleared. If you’re not sure, here are two resources to help: (1) _CHART: Which type of expungement am I eligible for?_ and (2) _How to Get a Felony Expunged in California_

@sydneywalcoff  - i'll make the update as soon as we confirm this.

2023-05-12 09:40 UTC, SamHyler commented
> @SamHyler - how about just using the article titles like below, except that they'd be underlined and not italic?
> 
> Be sure you are eligible to have your record cleared. If you’re not sure, here are two resources to help: (1) _CHART: Which type of expungement am I eligible for?_ and (2) _How to Get a Felony Expunged in California_
> 
> @sydneywalcoff - i'll make the update as soon as we confirm this.

The text needs to be very short here, so a hyperlink would be best. I'll pop it over to the team and get back to you with text for it.

2023-05-19 03:58 UTC, tglaz commented
@SamHyler  - just following up on the hyperlink question.

I can also go ahead and just do it in the original way if you want and we can follow up later if needed. Just say the word :)

2023-05-19 19:39 UTC, SamHyler commented
We are discussing in team and will get back to you after our next meeting on Friday https://github.com/hackforla/expunge-assist/issues/944

2023-05-26 00:23 UTC, sydneywalcoff approved these changes

2023-05-26 00:23 UTC, merged