Updated About Us Page
hackforla/expunge-assist pull request #920
Opened 2023-05-01 23:24 UTC by troymathis

*closes [703](https://github.com/hackforla/expunge-assist/issues/703)

**Changes I made**
---

- Added buttons and hyperlinks with correct redirect to those links
- Added english locale for entire page
- styles added for entire page (buttons, links, ul)

**Notes**

- Styles not to precise liking, did the best I can

2023-05-05 16:47 UTC, sydneywalcoff requested changes
Hey @troymathis! Thanks for submitting your PR. Looks great!

Just some small updates:
- Can you increase the line height for the text on the page? It looks a little more crowded than the figma. 
- On Desktop, can you left align the content with the expunge assist logo in the header? 
<img width="1440" alt="Screen Shot 2023-05-05 at 9 41 59 AM" src="https://user-images.githubusercontent.com/75542938/236518148-54ba5385-7a8a-4add-8b4c-c2da063db4ca.png">

2023-05-05 16:47 UTC, sydneywalcoff commented on package-lock.json
@troymathis can we remove this? The package-lock.json for this project is in the products/statement-generator folder. 

thank you!

2023-05-05 16:47 UTC, sydneywalcoff commented on .vscode/settings.json
@troymathis can you add this to your .gitignore and remove from the repository?

https://www.git-tower.com/learn/git/commands/git-rm/

2023-05-06 23:14 UTC, troymathis commented on package-lock.json
Was able to get rid of the crowded look but I'm not too sure if I can align the page without changing the styles of the ContentContainer. If I were to hardcode the align it would override the media queries of the ContentContainer and mess up the text wrap on browser resize. The FAQ and other pages that use it are also centered because of this btw. Should I just go ahead and change the styles?

2023-05-12 00:06 UTC, sydneywalcoff commented on package-lock.json
@troymathis Good point. No, let's leave it as is. Design wants to do a refactor of our components anyway

2023-05-19 00:01 UTC, sydneywalcoff requested changes

2023-05-19 00:01 UTC, sydneywalcoff commented on .vscode/settings.json
@troymathis hey sorry looks like this got left behind in your last update, can you remove it?

2023-05-26 00:34 UTC, sydneywalcoff requested changes

2023-05-26 00:34 UTC, sydneywalcoff commented on products/statement-generator/.vscode/settings.json
@troymathis hey @troymathis! Because you committed and pushed it to the remote repo, just adding .vscode to the gitignore will just ignore all _future_ changes. 
Can you try running this command?
`git rm -r --cached .vscode`
before committing and pushing again?

2023-05-26 00:35 UTC, sydneywalcoff approved these changes

2023-05-26 00:35 UTC, merged