Before you begin hyperlink and copy update #962
hackforla/expunge-assist pull request #994
Opened 2023-08-13 21:02 UTC by awellsbiz

Hi,

For issue #962, I have updated the hyperlinks for mobile and made the design changes per the figma document provided [here.](https://www.figma.com/file/hYqRxmBVtJbDv9DJXV6nra/Expunge-Assist-Main-Figma?type=design&node-id=10739%3A112003&t=JFzXfKekw4yZXp0T-1)

2023-08-15 04:06 UTC, sydneywalcoff requested changes
Hi @awellsbiz!

Thanks for submitting a PR! 🎉 I appreciate the quick turn-around.

Just a couple code corrections above. Otherwise, I noticed that some of the font-sizes are off. Can you double-check them?

Thank you! Slack me if you have any questions!

2023-08-15 17:53 UTC, awellsbiz commented on products/statement-generator/public/locales/en/translation.json
> +    "sectionParagraph1": "Be sure you are eligible to have your record cleared. If you’re not sure, the <a target='_blank' href='https://selfhelp.courts.ca.gov/clean-your-record'>California Courts Se
copy will work on this today

2023-08-19 06:15 UTC, awellsbiz commented
Hi @sydneywalcoff 

The changes have been made. Thanks for the CSS tips 😃

2023-08-22 20:36 UTC, sydneywalcoff approved these changes
@awellsbiz Thanks for getting these changes in! I'll get this merged

2023-08-22 20:36 UTC, merged